name: ng_scss_components
description: A minimal example to compile Sass files for each component.
version: 0.0.0
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: any
  dart_sass_transformer: any
  stream_transformers: '^0.3.0'
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- dart_sass_transformer
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
